# ----------
# dataset
# ----------
data_root: ./dataset/
n_classes: 21
classes:    ['aeroplane', 'bicycle', 'bird', 'boat',
            'bottle', 'bus', 'car', 'cat', 'chair',
            'cow', 'diningtable', 'dog', 'horse',
            'motorbike', 'person', 'pottedplant',
            'sheep', 'sofa', 'train', 'tvmonitor']
img_size: 256
n_channels: 3
color_mean: [0.485, 0.456, 0.406]
color_std: [0.229, 0.224, 0.225]
train_txt: train.txt
test_txt: val.txt
img_extension: .jpg
anno_extension: .png

# ----------------
# train parameters
# ----------------
lr: 0.0001
decay: 0.0001
n_gpus: 1
batch_size: 16
n_epochs: 50

# save_ckpt_interval should not be 0.
save_ckpt_interval: 50

# output dir (logs, results)
log_dir: ./logs/

# checkpoint path or blank
resume:
# e.g) resume: ./logs/2020-07-26T00:19:34.918002/ckpt/best_iou_ckpt.pth


# ----------------
# Visualize Results
# ----------------
# visualize label color_map
label_color_map: [
                [0, 0, 0],
                [128, 0, 0],
                [0, 128, 0],
                [128, 128, 0],
                [0, 0, 128],
                [128, 0, 128],
                [0, 128, 128],
                [128, 128, 128],
                [64, 0, 0],
                [192, 0, 0],
                [64, 128, 0],
                [192, 128, 0],
                [64, 0, 128],
                [192, 0, 128],
                [64, 128, 128],
                [192, 128, 128],
                [0, 64, 0],
                [128, 64, 0],
                [0, 192, 0],
                [128, 192, 0],
                [0, 64, 128],
                ]